### ISSUE TITLE
Could not index class ...

### ISSUE THREAD

**Issue by helio-frota** [wildfly/jandex#26]
Hi,
I found this error while trying jruby + wildfly-swarm
https://github.com/helio-frota/wildfly-swarm-jruby-sinatra

```
2015-12-08 00:08:48,378 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0003: Could not index class jnr/x86asm/SEGMENT.class at /wildfly-swarm-jruby-sinatra.war/WEB-INF/lib/jnr-x86asm-1.0.2.jar: java.lang.NullPointerException
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.Type.equals(Type.java:358)
    at org.jboss.jandex.StrongInternPool.eq(StrongInternPool.java:139)
    at org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:247)
    at org.jboss.jandex.NameTable.intern(NameTable.java:84)
    at org.jboss.jandex.Indexer.parseType(Indexer.java:1317)
    at org.jboss.jandex.Indexer.parseType(Indexer.java:1296)
    at org.jboss.jandex.Indexer.processFieldInfo(Indexer.java:287)
    at org.jboss.jandex.Indexer.index(Indexer.java:1445)
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

2015-12-08 00:08:48,380 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0003: Could not index class jnr/x86asm/Mem.class at /wildfly-swarm-jruby-sinatra.war/WEB-INF/lib/jnr-x86asm-1.0.2.jar: java.lang.NullPointerException
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.Type.equals(Type.java:358)
    at java.util.Arrays.equals(Arrays.java:2829)
    at org.jboss.jandex.StrongInternPool.eq(StrongInternPool.java:132)
    at org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:247)
    at org.jboss.jandex.NameTable.intern(NameTable.java:88)
    at org.jboss.jandex.Indexer.intern(Indexer.java:1038)
    at org.jboss.jandex.Indexer.processMethodInfo(Indexer.java:263)
    at org.jboss.jandex.Indexer.index(Indexer.java:1446)
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

2015-12-08 00:08:48,382 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0003: Could not index class jnr/x86asm/CpuInfo$Vendor.class at /wildfly-swarm-jruby-sinatra.war/WEB-INF/lib/jnr-x86asm-1.0.2.jar: java.lang.NullPointerException
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.Type.equals(Type.java:358)
    at java.util.Arrays.equals(Arrays.java:2829)
    at org.jboss.jandex.StrongInternPool.eq(StrongInternPool.java:132)
    at org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:247)
    at org.jboss.jandex.NameTable.intern(NameTable.java:88)
    at org.jboss.jandex.GenericSignatureParser.parseTypeList(GenericSignatureParser.java:365)
    at org.jboss.jandex.GenericSignatureParser.parseTypeArguments(GenericSignatureParser.java:340)
    at org.jboss.jandex.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:311)
    at org.jboss.jandex.GenericSignatureParser.parseClassSignature(GenericSignatureParser.java:249)
    at org.jboss.jandex.Indexer.parseClassSignature(Indexer.java:944)
    at org.jboss.jandex.Indexer.applySignatures(Indexer.java:960)
    at org.jboss.jandex.Indexer.index(Indexer.java:1449)
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

2015-12-08 00:08:48,384 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0003: Could not index class jnr/x86asm/SerializerIntrinsics.class at /wildfly-swarm-jruby-sinatra.war/WEB-INF/lib/jnr-x86asm-1.0.2.jar: java.lang.NullPointerException
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.DotName.equals(DotName.java:293)
    at org.jboss.jandex.Type.equals(Type.java:358)
    at java.util.Arrays.equals(Arrays.java:2829)
    at org.jboss.jandex.StrongInternPool.eq(StrongInternPool.java:132)
    at org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:247)
    at org.jboss.jandex.NameTable.intern(NameTable.java:88)
    at org.jboss.jandex.Indexer.intern(Indexer.java:1038)
    at org.jboss.jandex.Indexer.processMethodInfo(Indexer.java:263)
    at org.jboss.jandex.Indexer.index(Indexer.java:1446)
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:99)
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by helio-frota** [comment]
Reported in Jira
https://issues.jboss.org/browse/JANDEX-34
