### ISSUE TITLE
jandex related no such method exception

### ISSUE THREAD

**Issue by jcabrerazuniga** [wildfly/jandex#46]
My wildlfy 10.0.0.0 server (which I can not change since an application called i2b2 needs to work with) is sending me the next error:

[javax.enterprise.resource.webcontainer.jsf.application] (ServerService Thread Pool -- 73) java.lang.NoSuchMethodException: org.jboss.as.jsf.injection.JandexAnnotationProvider.<init>(javax.servlet.ServletContext, com.sun.faces.spi.AnnotationProvider): java.lang.NoSuchMethodException: org.jboss.as.jsf.injection.JandexAnnotationProvider.<init>(javax.servlet.ServletContext, com.sun.faces.spi.AnnotationProvider)

    at java.lang.Class.getConstructor0(Class.java:3082) [rt.jar:1.8.0_192]

    at java.lang.Class.getDeclaredConstructor(Class.java:2178) [rt.jar:1.8.0_192]

    at com.sun.faces.spi.ServiceFactoryUtils.getProviderFromEntry(ServiceFactory.java:83) [jsf-impl-2.2.12-jbossorg-2.jar:2.2.12-jbossorg-2]

    at com.sun.faces.spi.AnnotationProviderFactory.createAnnotationProvider(AnnotationProviderFactory.java:70) [jsf-impl-2.2.12-jbossorg-2.jar:2.2.12-jbossorg-2]

    at com.sun.faces.config.ConfigManager$AnnotationScanTask.<init>(ConfigManager.java:931) [jsf-impl-2.2.12-jbossorg-2.jar:2.2.12-jbossorg-2]

    at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:385) [jsf-impl-2.2.12-jbossorg-2.jar:2.2.12-jbossorg-2]

    at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:227) [jsf-impl-2.2.12-jbossorg-2.jar:2.2.12-jbossorg-2]

    at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187) [undertow-servlet-1.3.23.Final.jar:1.3.23.Final]

    at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:198) [undertow-servlet-1.3.23.Final.jar:1.3.23.Final]

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)

    at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)

    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_192]

    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_192]

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_192]

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_192]

    at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_192]

    at org.jboss.threads.JBossThread.run(JBossThread.java:320)

 
Can you please tell me what version of jandex I need to upload into my wildfly server to avoid this error? My server has jandex so I will truly need to upgrade it. If you can provide some instructions also this could be great (I am kind of new to wildfly and jandex)
thanks a lot

**Comment by n1hility** [comment]
Closing due to age, if you still see the issue please reopen with more details
