### ISSUE TITLE
Add classname to "Required class information is missing" error

### ISSUE THREAD

**Issue by vlsi** [wildfly/jandex#92]
See https://github.com/wildfly/jandex/blob/7f2c075ba9246e4b6cc8fe7f3e3678dc2b64891c/src/main/java/org/jboss/jandex/Indexer.java#L926

The error message is hard to understand, and the root cause is not clear.

What do you think if the error includes the class name or something else for making the exception actionable?

The current exception:

```
Caused by: java.lang.IllegalStateException: Required class information is missing
         at org.jboss.jandex.Indexer.rebuildNestedType(Indexer.java:926)
         at org.jboss.jandex.Indexer.resolveTypePath(Indexer.java:786)
         at org.jboss.jandex.Indexer.resolveTypeAnnotation(Indexer.java:705)
         at org.jboss.jandex.Indexer.resolveTypeAnnotations(Indexer.java:613)
         at org.jboss.jandex.Indexer.index(Indexer.java:1602)
         at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.toClassDescriptor(ClassFileArchiveEntryHandler.java:64)
         at org.hibernate.boot.archive.scan.spi.ClassFileArchiveEntryHandler.handleEntry(ClassFileArchiveEntryHandler.java:52)
```

Context: https://www.postgresql.org/message-id/AM0PR04MB652919E6F344C84DC3073D0D96140%40AM0PR04MB6529.eurprd04.prod.outlook.com

**Comment by vlsi** [comment]
Another exception:

```
            Caused by: java.lang.IllegalStateException: Class extends type annotation appeared on a non class target
                at org.jboss.jandex.Indexer.processTypeAnnotation(Indexer.java:538)
                at org.jboss.jandex.Indexer.processTypeAnnotations(Indexer.java:515)
                at org.jboss.jandex.Indexer.processAttributes(Indexer.java:355)
                at org.jboss.jandex.Indexer.processMethodInfo(Indexer.java:306)
                at org.jboss.jandex.Indexer.index(Indexer.java:1602)
```

**Comment by n1hility** [comment]
thanks for the report

**Comment by vlsi** [comment]
Reproducer:

```java
    public static class IteratorSupplier implements Supplier<Consumer<@Nullable Object[]>> {
        @Override
        public Consumer<@Nullable Object[]> get() {
            return new Consumer<@Nullable Object[]>() {
                @Override
                public void accept(@Nullable Object[] objects) {
                }
            };
        }
    }
```

Then parse `IteratorSupplier$1.class` (==class file for the anonymous `new Consumer`)

**Comment by vlsi** [comment]
This might be relevant: https://bugs.openjdk.java.net/browse/JDK-8198945, so it might be yet another `javac` issue :-/
